export interface ProductSpecs {
  title: string;
  subTitle: string;
  category: string;
  subCategory: string;
  size: string;
  material: string;
  endConnection: string;
  pressureRating: string;
  modeOfOperation: string;
  manufacturingStandard: string;
  testingStandard: string;
  seatLiner?: string;
  seat?: string;
}

export const productSpecsRegistry: Record<string, ProductSpecs> = {
  // Ball Valve - Floating Design
  "ball-valve/floating-design/2-piece-design-screwed-1000-wog": {
    title: "Floating Design",
    subTitle: "2 Piece Design screwed 1000 WOG",
    category: "Ball valve",
    subCategory: "Floating Design",
    size: "DN6 - DN100",
    material: "CF8 / CF8M / CF3 / CF3M",
    endConnection: "BSPF / NPTF",
    pressureRating: "150# / 300# / 1000 PSI",
    modeOfOperation: "Lever",
    manufacturingStandard: "ISO 17292",
    testingStandard: "ISO 5208",
  },
  "ball-valve/floating-design/3-piece-design-screwed-socket-weld-150-300": {
    title: "Floating Design",
    subTitle: "3 Piece Design Screwed / Socket weld 150# & 300#",
    category: "Ball valve",
    subCategory: "Floating Design",
    size: "DN6 - DN100",
    material: "WCB / CF8 / CF8M / CF3 / CF3M",
    endConnection: "BSPF / NPTF / SW / BW",
    pressureRating: "150# / 300#",
    modeOfOperation: "Lever, Actuator",
    manufacturingStandard: "ISO 17292",
    testingStandard: "ISO 5208",
  },
  "ball-valve/floating-design/3-piece-design-screwed-socket-weld-600-800-1500": {
    title: "Floating Design",
    subTitle: "3 Piece Design Screwed / Socket weld 600# & 800# & 1500#",
    category: "Ball valve",
    subCategory: "Floating Design",
    size: "DN6 - DN50",
    material: "A105 / F304/L / F316/L / CF8 / CF8M / CF3 / CF3M",
    endConnection: "BSPF / NPTF / SW / BW",
    pressureRating: "600# / 800# / 1500#",
    modeOfOperation: "Lever, Actuator",
    manufacturingStandard: "ISO 17292 / API 6D / API 608",
    testingStandard: "ISO 5208 / ISO 10497 / API 607",
  },
  "ball-valve/floating-design/3-piece-design-flanged-ansi-150-300-600-900": {
    title: "Floating Design",
    subTitle: "3 Piece Design Flanged ANSI 150#, 300#, 600# & 900#",
    category: "Ball valve",
    subCategory: "Floating Design",
    size: "DN6 - DN300",
    material: "A105 / F304/L / F316/L / WCB / CF8 / CF8M / CF3 / CF3M",
    endConnection: "FLANGED / BW",
    pressureRating: "150# / 300# / 600# / 900#",
    modeOfOperation: "Lever, Actuator",
    manufacturingStandard: "ISO 17292 / API 6D / API 608",
    testingStandard: "ISO 5208 / ISO 10497 / API 607",
  },
  "ball-valve/floating-design/2-piece-design-flanged-ansi-150-300-600": {
    title: "Floating Design",
    subTitle: "2 Piece Design Flanged ANSI 150#, 300#, 600#",
    category: "Ball valve",
    subCategory: "Floating Design",
    size: "DN6 - DN300",
    material: "WCB / CF8 / CF8M / CF3 / CF3M",
    endConnection: "FLANGED",
    pressureRating: "150# / 300# / 600#",
    modeOfOperation: "Lever, Actuator",
    manufacturingStandard: "ISO 17292 / API 6D / API 608",
    testingStandard: "ISO 5208 / ISO 10497 / API 607",
  },
  "ball-valve/floating-design/wafer-design-ball-valve-150-pn25-pn40": {
    title: "Floating Design",
    subTitle: "Wafer Design Ball valve 150# / PN25 / PN40",
    category: "Ball valve",
    subCategory: "Floating Design",
    size: "DN50 - DN150",
    material: "WCB / CF8 / CF8M / CF3 / CF3M",
    endConnection: "Wafer to suit ANSI / ND flanges",
    pressureRating: "150# / PN25 / PN40",
    modeOfOperation: "Lever, Actuator",
    manufacturingStandard: "ISO 17292",
    testingStandard: "ISO 5208",
  },

  // Ball Valve - Trunnion Mounted
  "ball-valve/trunnion-mounted/2-piece-design-flanged-ansi-150-300-600": {
    title: "Trunnion Mounted",
    subTitle: "2 Piece Design Flanged ANSI 150#, 300#, 600#",
    category: "Ball valve",
    subCategory: "Trunnion Mounted",
    size: "DN100 - DN300",
    material: "WCB / CF8 / CF8M / CF3 / CF3M",
    endConnection: "FLANGED",
    pressureRating: "150# / 300# / 600#",
    modeOfOperation: "Lever, Actuator",
    manufacturingStandard: "ISO 17292 / API 6D / API 608",
    testingStandard: "ISO 5208 / ISO 10497 / API 607",
  },
  "ball-valve/trunnion-mounted/3-piece-design-flanged-ansi-150-300-600": {
    title: "Trunnion Mounted",
    subTitle: "3 Piece Design Flanged ANSI 150#, 300#, 600#",
    category: "Ball valve",
    subCategory: "Trunnion Mounted",
    size: "DN100 - DN300",
    material: "WCB / CF8 / CF8M / CF3 / CF3M",
    endConnection: "FLANGED",
    pressureRating: "150# / 300# / 600#",
    modeOfOperation: "Lever, Actuator",
    manufacturingStandard: "ISO 17292 / API 6D / API 608",
    testingStandard: "ISO 5208 / ISO 10497 / API 607",
  },

  // Butterfly Valve - Centric Disc Design
  "butterfly-valve/centric-disc-design/wafer-semi-lugged-pn10-pn16-pn20-pn25": {
    title: "Centric Disc Design",
    subTitle: "Wafer Semi Lugged PN10# / PN16# / PN20# / PN25#",
    category: "Butterfly valve",
    subCategory: "Centric Disc Design",
    size: "DN40 - DN1000",
    material: "CI / DI / WCB / CF8 / CF8M / CF3 / CF3M / DSS / SDS / AL. BR",
    seatLiner: "BUNA-N, EPDM, SILICON, VITON",
    endConnection: "Wafer to suit ANSI & ND flanges",
    pressureRating: "PN10# / PN16# / PN20# / PN25#",
    modeOfOperation: "Lever, Gear, Actuator",
    manufacturingStandard: "API 609 (Cat.A)",
    testingStandard: "API 598",
  },
  "butterfly-valve/centric-disc-design/full-lugged-pn10-pn16-pn20-pn25": {
    title: "Centric Disc Design",
    subTitle: "Full Lugged PN10# / PN16# / PN20# / PN25#",
    category: "Butterfly valve",
    subCategory: "Centric Disc Design",
    size: "DN40 - DN1000",
    material: "CI / DI / WCB / CF8 / CF8M / CF3 / CF3M / DSS / SDS / AL. BR",
    seatLiner: "BUNA-N, EPDM, SILICON, VITON",
    endConnection: "Lugged to suit ANSI & ND flanges",
    pressureRating: "PN10# / PN16# / PN20# / PN25#",
    modeOfOperation: "Lever, Gear, Actuator",
    manufacturingStandard: "API 609 (Cat.A)",
    testingStandard: "API 598",
  },
  "butterfly-valve/centric-disc-design/wafer-flanged-pn10-pn16-pn20-pn25": {
    title: "Centric Disc Design",
    subTitle: "Wafer Flanged PN10# / PN16# / PN20# / PN25#",
    category: "Butterfly valve",
    subCategory: "Centric Disc Design",
    size: "DN40 - DN1000",
    material: "CI / DI / WCB / CF8 / CF8M / CF3 / CF3M / DSS / SDS / AL. BR",
    seatLiner: "BUNA-N, EPDM, SILICON, VITON",
    endConnection: "Flanged to suit ANSI & ND flanges",
    pressureRating: "PN10# / PN16# / PN20# / PN25#",
    modeOfOperation: "Lever, Gear, Actuator",
    manufacturingStandard: "API 609 (Cat.A)",
    testingStandard: "API 598",
  },
  "butterfly-valve/centric-disc-design/double-flanged-pn10-pn16-pn20-pn25": {
    title: "Centric Disc Design",
    subTitle: "Double Flanged PN10# / PN16# / PN20# / PN25#",
    category: "Butterfly valve",
    subCategory: "Centric Disc Design",
    size: "DN40 - DN1000",
    material: "CI / DI / WCB / CF8 / CF8M / CF3 / CF3M / DSS / SDS / AL. BR",
    seatLiner: "BUNA-N, EPDM, SILICON, VITON",
    endConnection: "Flanged",
    pressureRating: "PN10# / PN16# / PN20# / PN25#",
    modeOfOperation: "Lever, Gear, Actuator",
    manufacturingStandard: "API 609 (Cat.A)",
    testingStandard: "API 598",
  },

  // Butterfly Valve - Double Offset Design
  "butterfly-valve/double-offset-design/wafer-semi-lugged-150-300": {
    title: "Double Offset Design",
    subTitle: "Wafer Semi Lugged 150# / 300#",
    category: "Butterfly valve",
    subCategory: "Double Offset Design",
    size: "DN40 - DN1000",
    material: "WCB / CF8 / CF8M / CF3 / CF3M / DSS / SDS / AL. BR",
    seat: "PTFE / CFT / GFT",
    endConnection: "Wafer to suit ANSI & ND flanges",
    pressureRating: "150# / 300#",
    modeOfOperation: "Lever, Gear, Actuator",
    manufacturingStandard: "API 609 (Cat.A)",
    testingStandard: "API 598",
  },
  "butterfly-valve/double-offset-design/full-lugged-150-300": {
    title: "Double Offset Design",
    subTitle: "Full Lugged 150# / 300#",
    category: "Butterfly valve",
    subCategory: "Double Offset Design",
    size: "DN40 - DN1000",
    material: "WCB / CF8 / CF8M / CF3 / CF3M / DSS / SDS / AL. BR",
    seat: "PTFE / CFT / GFT",
    endConnection: "Lugged to suit ANSI & ND flanges",
    pressureRating: "150# / 300#",
    modeOfOperation: "Lever, Gear, Actuator",
    manufacturingStandard: "API 609 (Cat.A)",
    testingStandard: "API 598",
  },
  "butterfly-valve/double-offset-design/double-flanged-150-300": {
    title: "Double Offset Design",
    subTitle: "Double Flanged 150# / 300#",
    category: "Butterfly valve",
    subCategory: "Double Offset Design",
    size: "DN40 - DN1000",
    material: "WCB / CF8 / CF8M / CF3 / CF3M / DSS / SDS / AL. BR",
    seat: "PTFE / CFT / GFT",
    endConnection: "Flanged to suit ANSI flanges",
    pressureRating: "150# / 300#",
    modeOfOperation: "Lever, Gear, Actuator",
    manufacturingStandard: "API 609 (Cat.A)",
    testingStandard: "API 598",
  },
};